universe            = vanilla
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
RequestCpus = 4
output = ../condor_logs/job_$(Cluster)_$(Process).out
error  = ../condor_logs/job_$(Cluster)_$(Process).err
log    = ../condor_logs/job_$(Cluster).log
+JobFlavour = "espresso"

# Define all jobs using a queue with variables
queue executable,arguments from (
    runJobCosmic.sh, "mini_dir_1 cosmicsMC_1.root
    runJobCosmic.sh, "mini_dir_2 cosmicsMC_2.root"
    runJobCosmic.sh, "mini_dir_3 cosmicsMC_3.root"
    runJobCosmic.sh, "mini_dir_4 cosmicsMC_4.root"
    runJobCosmic.sh, "mini_dir_5 cosmicsMC_5.root"
    runJobCosmic.sh, "mini_dir_6 cosmicsMC_6.root"
    runJobCosmic.sh, "mini_dir_7 cosmicsMC_7.root"
    runJobCosmic.sh, "mini_dir_8 cosmicsMC_8.root"
    runJobCosmic.sh, "mini_dir_9 cosmicsMC_9.root"
    runJobCosmic.sh, "mini_dir_10 cosmicsMC_10.root"
)